project:
  type: website

website:
  title: "ASA DataFest 2025"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - DataFest has concluded. Thank you all for making it such a special event! Check-in on this website for photos of the event."
    type: primary
    position: below-navbar
  navbar:
    search: true
    left:
      - text: About DataFest
        href: index.qmd
      - text: Register
        href: register.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Volunteer sign-up
        href: volunteers.qmd
      - text: Data access
        href: data.qmd
      - text: Room assignment
        href: room_assign.qmd
    tools:
      - icon: envelope-at
        href: mailto:cstratton@middlebury.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


# quarto render
# quarto publish gh-pages