project:
  type: website

website:
  title: "ASA DataFest 2025"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - DataFest starts tonight at 6:00 in Bi-Hall!"
    type: primary
    position: below-navbar
  navbar:
    search: true
    left:
      - text: About DataFest
        href: index.qmd
      - text: Register
        href: register.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Volunteer sign-up
        href: volunteers.qmd
    tools:
      - icon: envelope-at
        href: mailto:stats@middlebury.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


# quarto render
# quarto publish gh-pages