project:
  type: website

website:
  title: "ASA DataFest 2025"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
    tools:
      - icon: envelope-at
        href: mailto:cstratton@middlebury.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


# quarto render
# quarto publish gh-pages